<?php

namespace PHRentals\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{
	
	public function findAjaxValue($term)
	{
		$qb = $this->getEntityManager()->createQueryBuilder();
		$query = $qb->select('c')
		->from('PHRentalsMainBundle:Project','c')
		->andWhere('c.name LIKE \'%'.str_replace('\'', '\'\'', $term).'%\'');
	
		$projects = $qb->getQuery()->getResult();
	
		return $projects;
	}
	
	public function createSlug($project)
	{
	
		$slug = $project->getName().'-';
	
		if($project->getAddress()->getDistrict()) {
			$slug .= $project->getAddress()->getDistrict()->getName();
		}
	
		$slug .= '-'.$project->getId();
	
		$clean = iconv('UTF-8', 'ASCII//TRANSLIT', $slug);
		$clean = preg_replace("/[^a-zA-Z0-9\/_|+ -]/", '', $clean);
		$clean = strtolower(trim($clean, '-'));
		$clean = preg_replace("/[\/_|+ -]+/", "-", $clean);
	
		//$slug = mysql_real_escape_string($clean);
	
		$slug = $clean;
	
		return $slug;
	}	
	
}
