<?php

namespace PHRentals\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends EntityRepository
{
	public function getValueByKey($key) {
		$sort_order = $this->getEntityManager()
		->createQuery('SELECT s.value FROM PHRentalsMainBundle:Settings s WHERE s.name = :key')
		->setParameter('key', $key)
		->getResult(Query::HYDRATE_SINGLE_SCALAR);
	 	return $sort_order;
	}
	
	public function findSeasonDates() {
		$dates = $this->getEntityManager()
		->createQuery('SELECT s.name, s.value FROM PHRentalsMainBundle:Settings s WHERE s.name = \'lowSeasonDates\' OR s.name= \'highSeasonDates\' OR s.name= \'peakSeasonDates\'')
		->getResult();
		
		$seasonDates = array();
		
		foreach($dates as $date) {
			$date_set = explode(',',$date['value']);
			$i=1;
			foreach($date_set as $date_pair) {
				$date_from_to = explode('-',$date_pair);
				$seasonDates[$date['name']][$i]['from'] = $date_from_to[0];
				$seasonDates[$date['name']][$i]['to'] = $date_from_to[1];
				$i++;
			}
			
			
		}
		return $seasonDates;
	}
	
	
}
